flaskr/auth.py
import functools

from flask import (Blueprint, flash, g, redirect, render_template, request,
                   session, url_for)
from flask_login import current_user, login_user, logout_user
from werkzeug.security import check_password_hash, generate_password_hash

from app import db
from flaskr.models import User

from .forms import LoginForm, RegistrationForm

bp = Blueprint('auth', __name__, template_folder='Templates')
@bp.route('/')
@bp.route('/index')
def index():
    user = current_user
    return render_template('index.html', title='Home', user=user)

@bp.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('auth.index'))


@bp.route('/login', methods=('GET', 'POST'))
def login():
    if current_user.is_authenticated:
        return redirect(url_for('auth.index'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user is None or not user.check_password(form.password.data):
            flash('Invalid username or password')
            return redirect(url_for('login'))
        login_user(user, remember=form.remember_me.data)
        return redirect(url_for('auth.index'))
    return render_template('login.html', title='Sign In', form=form)

@bp.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('auth.index'))
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(username=form.username.data, email=form.email.data)
        user.set_password(form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('Congratulations, you are now a registered user!')
        return redirect(url_for('auth.login'))
    return render_template('register.html', title='Register', form=form)

# @bp.before_app_request
# def load_logged_in_user():
#     user_id = session.get('user_id')

#     if user_id is None:
#         g.user = None
#     else:
#         g.user = get_db().execute(
#             'SELECT * FROM user WHERE id = ?', (user_id,)
#         ).fetchone()

# @bp.route('/logout')
# def logout():
#     session.clear()
#     return redirect(url_for('index'))

# def login_required(view):
#     @functools.wraps(view)
#     def wrapped_view(**kwargs):
#         if g.user is None:
#             return redirect(url_for('auth.login'))

#         return view(**kwargs)

#     return wrapped_view

flaskr/templates/account_settings.html
{% extends "base.html" %}

{% block content %}
    <h1>Account Settings</h1>
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <p>
            {{ form.new_username.label }}<br>
            {{ form.new_username(size=32) }}<br>
            {% for error in form.new_username.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>{{ form.submit_new_username() }}</p>
        <p>
            {{ form.new_email.label }}<br>
            {{ form.new_email(size=64) }}<br>
            {% for error in form.new_email.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>{{ form.submit_new_email() }}</p>
        <p>
            {{ form.password.label }}<br>
            {{ form.password(size=32) }}<br>
            {% for error in form.password.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.new_password.label }}<br>
            {{ form.new_password(size=32) }}<br>
            {% for error in form.new_password.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.new_password2.label }}<br>
            {{ form.new_password2(size=32) }}<br>
            {% for error in form.new_password2.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>{{ form.submit_new_password() }}</p>
    </form>
{% endblock %}

flaskr/templates/base.html
<!doctype html>
{% with messages = get_flashed_messages() %}
  {% if messages %}
    <ul class=flashes>
    {% for message in messages %}
      <li>{{ message }}</li>
    {% endfor %}
    </ul>
  {% endif %}
{% endwith %}
<div>
  Beat-the-BM
  <a href="/index">Home</a>
  {% if current_user.is_anonymous %}
  <a href="{{ url_for('auth.login') }}">Login</a>
  {% else %}
  <a href="{{ url_for('auth.logout') }}">Logout</a>
  {% endif %}
  <a href="/new_feature">Create feature</a>
  <a href="/new_modeltype">Create modeltype</a>
  <a href="/new_model">Create model</a>
  <a href="/feature_overview">All features</a>
  <a href="/user_overview">All users</a>
  <a href="/model_overview">All models</a>
  <a href="/admin">Admin</a>
</div>
<section class="content">
  <body>
    <hr>
    {% block content %}
    {% endblock %}
  </body>
</section>

flaskr/templates/feature_create.html
{% extends "base.html" %}

{% block content %}
    <h1>{{ title }}</h1>
    <form action="" method="post" novalidate>
        {{ form.hidden_tag() }}
        <p>
            {{ form.featurename.label }}<br>
            {{ form.featurename(size=32) }}
        </p>
        <p>{{ form.submit() }}</p>
    </form>
{% endblock %}

flaskr/templates/feature_view_edit.html
{% extends "base.html" %}

{% block content %}
    <h1>Add feature</h1>
    <form action="" method="post" novalidate>
        {{ form.hidden_tag() }}
        <p>
            {{ form.featurename.label }}<br>
            {{ form.featurename(size=32) }}
        </p>
        <p>{{ form.submit() }}</p>
    </form>
{% endblock %}

flaskr/templates/index.html
{% extends "base.html" %}

{% block content %}
{% if current_user.is_anonymous %}
<h1> Hello User! </h1>
{% else %}
<h1> Hello {{ user.username }}! </h1>
{% endif %}
<form method="post" action="/">
    <input type="submit" value="API" name="action1"/>
</form>
<form method="post" action="/">
    <input type="submit" value="train" name="action2"/>
</form>
<form method="post" action="/">
    <input type="submit" value="predict" name="action3"/>
</form>
{% endblock %}

flaskr/templates/login.html
{% extends "base.html" %}

{% block content %}
    <h1>Sign In</h1>
    <form action="" method="post" novalidate>
        {{ form.hidden_tag() }}
        <p>
            {{ form.username.label }}<br>
            {{ form.username(size=32) }}
        </p>
        <p>
            {{ form.password.label }}<br>
            {{ form.password(size=32) }}
        </p>
        <p>{{ form.remember_me() }} {{ form.remember_me.label }}</p>
        <p>{{ form.submit() }}</p>
    </form>
    <p>New User? <a href="{{ url_for('auth.register') }}">Click to Register!</a></p>
{% endblock %}

flaskr/templates/model_create.html
{% extends "base.html" %}

{% block content %}
    <h1>{{ title }}</h1>
    <form action="" method="post" novalidate>
        {{ form.hidden_tag() }}
        <p>
            {{ form.name.label }}<br>
            {{ form.name(size=32) }}
        </p>
        <p>
            {{ form.number_of_last_games.label }}<br>
            {{ form.number_of_last_games(size=32) }}
        </p>
        <p>
            {{ form.modeltype.label }}<br>
            {{ form.modeltype(size=32) }}
        </p>
        <p>
            {{ form.features.label }}<br>
            {{ form.features(size=32) }}
        </p>
        <p>
            {{ form.seasons.label }}<br>
            {{ form.seasons(size=32) }}
        </p>
        <p>{{ form.submit() }}</p>
    </form>
{% endblock %}

flaskr/templates/modeltype_create.html
{% extends "base.html" %}

{% block content %}
    <h1>{{ title }}</h1>
    <form action="" method="post" novalidate>
        {{ form.hidden_tag() }}
        <p>
            {{ form.modeltype.label }}<br>
            {{ form.modeltype(size=32) }}
        </p>
        <p>{{ form.submit() }}</p>
    </form>
{% endblock %}

flaskr/templates/overview.html
{% extends "base.html" %}

{% block content %}
<table>
    <tr>
    {% for attr_name in attributes %}
        <th>{{ attr_name }}</th>
    {% endfor %}
      </tr>
    {% for attr_list in attr_lists %}
        <tr>
        {% for attr in attr_list %}
            <td>{{ attr }}</td>
        {% endfor %}
        </tr>
    {% endfor %}
</table>
{% endblock %}

flaskr/templates/register.html
{% extends "base.html" %}

{% block content %}
    <h1>Register</h1>
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <p>
            {{ form.username.label }}<br>
            {{ form.username(size=32) }}<br>
            {% for error in form.username.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.email.label }}<br>
            {{ form.email(size=64) }}<br>
            {% for error in form.email.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.password.label }}<br>
            {{ form.password(size=32) }}<br>
            {% for error in form.password.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.password2.label }}<br>
            {{ form.password2(size=32) }}<br>
            {% for error in form.password2.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>{{ form.submit() }}</p>
    </form>
{% endblock %}